image: "ruby:2.3"

variables:
  LC_ALL: C.UTF-8
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8

before_script:
  - ./prep_publish.sh

stages:
  -  build-pages

pages:
  stage: build-pages
  script:
    - ruby publish_apiary_docs.rb
  artifacts:
    paths:
      - public
