FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Performance Horizon API

# Group User

## User [/user]

A User can have permissions against multiple Publisher and Advertiser accounts.

+ Attributes (object)
    + user_id: 300621 - ID of the user
    + Include User Base
    + network_id: 1
    + network_name: PHG
    + `user_api_key`: ZMEt5ca8
    + Include Meta Info

### Retrieve User [GET]

Retrieve the details of the authenticated user.

+ Response 200 (application/json)
    + Attributes
        + user (User)

### Create an User [POST]

+ Request (application/json)
    + Attributes (User Base)
        + password: samplepass (required) - Password of the user

+ Response 200 (application/json)
    + Attributes
        + user (User)

# Group Publisher

## Publisher [/user/publisher]

+ Attributes
    + publisher_id: 300254 - ID of the publisher
    + account_name: publisherdemo
    + network_status (Status)

### Retreive Publisher [GET /user/publisher/{publisher_id}]

+ Parameters
    + publisher_id: 300254 - ID of the publisher

+ Response 200 (application/json)
    + Attributes
        + publisher (Publisher)

# Group Advertiser

## Advertiser [/user/advertiser]

+ Attributes (object)
    + advertiser_id: 300309 - ID of the advertiser
    + account_name: demoadvertiser
    + status (Status)
    + pre_payment - FIXME
    + current_balance - FIXME
    + Include Phone
    + Include Address
    + vat_number: 636136773 (number)
    + company_name: PHG Demo Advertiser
    + contact_email: kristin.bouveng@performancehorizon.com
    + default_currency: EUR
    + payment_currency: GBP
    + `budget_summary_interval` - FIXME
    + `budget_summary_start_time` - FIXME
    + Include Meta Info

### Retreive Advertiser [GET /user/advertiser/{advertiser_id}]

+ Parameters
    + advertiser_id: 300309 - ID of the advertiser

+ Response 200 (application/json)
    + Attributes
        + advertiser (Advertiser)

# Group Network

## Network [/network]

+ Attributes (object)
    + network_id: 1 - ID of the network
    + network_name: PHG - Name of the network
    + network_description: PHG Network - Description of the network
    + network_notes: Internal PHG Network - Any additional notes for the network
    + `network_application_id`: 2
    + `auto_approve_publishers` (Yes Or No)
    + `default_campaign_id` - FIXME:null
    + `cm_client_id`: b4d0d85c2cff813cdce092c261b2b200
    + `network_contact_email` - FIXME:null
    + network_locale (Locale)

### List Networks [GET]

+ Response 200 (application/json)
    + Attributes
        + networks (array[Network])

# Data Structures

## User Base (object)
+ user_name: demomaster (required) - Username of the user
+ email_address: matthew.clarke@performancehorizon.com (required) - Email address registered to the user
+ firstname: Pete (required) - First name of the user
+ lastname: CheyneWins (required) - Surname of the user
+ Include Phone
+ fax: 123456 (number) - Fax number
+ Include Address
+ locale (Locale)

## Address (object)
+ address1: Gardegasse 11 (required) - 1st line of the address
+ address2: Top 7 - 2nd line of the address
+ address3: London - 3rd line of the address
+ address4 - 4th line of the address
+ country (Country) (required) - Country of the address
+ postcode: `A-101` (required) - Postcode/Zipcode attached to the address

## Phone (object)
+ phone: 01595725007 (required) - Primary contact telephone number
+ phone_area - FIXME:null

## Meta Info (object)
+ signup_ip: 178.23.129.160
+ created: `2011-08-20 17:56:23`

## Yes Or No (enum)
+ y - yes
+ n - no
+ Sample: y

## Status (enum)
+ a - Approved
+ p - Pending
+ r - Rejected
+ Sample: a

## Country (enum)
+ GB - Great Britain
+ JP - Japan
+ Sample: GB

## Locale (enum)
+ en - English
+ Sample: en
