FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Performance Horizon API

# Group User

## User [/user]

A User can have permissions against multiple Publisher and Advertiser accounts.

+ Attributes (object)
    + user_id: 300621 - ID of the user
    + Include User Base
    + network_id: 1
    + network_name: PHG
    + `user_api_key`: ZMEt5ca8
    + Include Meta Info

### Retrieve User [GET]

Retrieve the details of the authenticated user.

+ Response 200 (application/json)
    + Attributes
        + user (User)

### Create an User [POST]

+ Request (application/json)
    + Attributes (User Base)
        + password: samplepass (required) - Password of the user

+ Response 200 (application/json)
    + Attributes
        + user (User)

### Update an User [POST /user/{user_id}]

+ Parameters
    + user_id: 300621 - ID of the user

# Group Publisher

## Publishers [/user/publisher]

### List Publishers [GET]

List all the publishers of the network that can be accessed by the authenticated user

+ Response 200 (application/json)
    + Attributes
        + publisher (array[Publisher Wrapper])

### Create a Publisher [POST]

+ Request (application/json)
    + Attributes (Publisher Base)

+ Response 200 (application/json)
    + Attributes (Publisher Wrapper)

## Publisher [/user/publisher/{publisher_id}]

+ Parameters
    + publisher_id: 300254 - ID of the publisher

+ Attributes
    + publisher_id: 300254 - ID of the publisher
    + Include Publisher Base
    + description - Description of the publisher FIXME:null
    + company_name: Demo Publisher
    + company_division
    + operating_country (Country)
    + network_status (Status)
    + network_id: 1 - ID of the network this publisher belongs to
    + network_notes
    + created_by: 300621 - ID of the user who created this publisher
    + reporting_timezone (Timezone)
    + week_start: Monday
    + Include Phone
    + contact_name: Pete Cheyne
    + contact_email: demo@performancehorizon.com
    + contact_locale (Locale)
    + im_provider: Skype
    + im_username: elisangis
    + campaign_select
    + `is_lead_user` (YesOrNo)
    + `is_affliate_user` (YesOrNo)
    + `is_foreign_network` (YesOrNo)
    + foreign_identifier
    + reporting_identifier
    + default_currency (Currency)
    + vat_number
    + `uk_vat_registered`
    + gst_registered
    + `us_tax_state`
    + abn
    + Include Meta Info

### Retreive Publisher [GET]

+ Response 200 (application/json)
    + Attributes
        + publisher (Publisher)

### Update Publisher [POST]

# Group Publisher Website

Authenticated user must have access to the publisher account

## Publisher Websites [/user/publisher/{publisher_id}/website]

+ Parameters
    + publisher_id: 300254 - ID of the publisher

### List all Publisher Websites [GET]

List all the websites attached to the given publisher account

+ Response 200 (application/json)
    + Attributes
        + websites (array[Publisher Website Wrapper])

### Create Publisher Website [POST]

Create and add a new website for the given publisher account

+ Request (application/json)
    + Attributes (Publisher Website Base)

+ Response 200 (application/json)
    + Attributes
        + websites (array[Publisher Website Wrapper])

## Publisher Website [/user/publisher/{publisher_id}/website/{website_id}]

+ Parameters
    + publisher_id: 300254 - ID of the publisher
    + website_id: 300029 - ID of the publisher website

+ Attributes
    + website_id: 300029 - ID of the publisher website
    + publisher_id: 300254 - ID of the publisher the website belongs to
    + Include Publisher Website Base
    + active (YesOrNo)
    + created_by: 300621 - ID of the user who created this publisher website
    + Include Created

### Retrieve a Publisher Website [GET]

Retrieve the information about the specified publisher website

+ Response 200 (application/json)
    + Attributes
        + website (Publisher Website)

### Update a Publisher Website [POST]

Update the specified publisher website

# Group Advertiser

## Advertiser [/user/advertiser]

+ Attributes (object)
    + advertiser_id: 300309 - ID of the advertiser
    + account_name: demoadvertiser
    + status (Status)
    + pre_payment - FIXME
    + current_balance - FIXME
    + Include Phone
    + Include Address
    + vat_number: 636136773 (number)
    + company_name: PHG Demo Advertiser
    + contact_email: kristin.bouveng@performancehorizon.com
    + default_currency (Currency)
    + payment_currency (Currency)
    + `budget_summary_interval` - FIXME
    + `budget_summary_start_time` - FIXME
    + Include Meta Info

### Retreive Advertiser [GET /user/advertiser/{advertiser_id}]

+ Parameters
    + advertiser_id: 300309 - ID of the advertiser

+ Response 200 (application/json)
    + Attributes
        + advertiser (Advertiser)

# Group Network

## Network [/network]

+ Attributes (object)
    + network_id: 1 - ID of the network
    + network_name: PHG - Name of the network
    + network_description: PHG Network - Description of the network
    + network_notes: Internal PHG Network - Any additional notes for the network
    + `network_application_id`: 2
    + `auto_approve_publishers` (Yes Or No)
    + `default_campaign_id` - FIXME:null
    + `cm_client_id`: b4d0d85c2cff813cdce092c261b2b200
    + `network_contact_email` - FIXME:null
    + network_locale (Locale)

### List Networks [GET]

Retrieve the details of the authenticated network.

+ Response 200 (application/json)
    + Attributes
        + networks (array[Network Wrapper])

# Data Structures

## User Base (object)
+ user_name: demomaster (required) - Username of the user
+ email_address: matthew.clarke@performancehorizon.com (required) - Email address registered to the user
+ firstname: Pete (required) - First name of the user
+ lastname: CheyneWins (required) - Surname of the user
+ Include Phone
+ fax: 123456 (number) - Fax number
+ Include Address
+ locale (Locale)
+ Include Signup IP

## Publisher Base (object)
+ account_name: publisherdemo (required)
+ vertical_name: Other
+ vertical: 10 (required)
+ `promotional_method_name`: Portal
+ promotional_method: 10 (required)
+ Include Signup IP

## Publisher Website Base (object)
+ website_url: http://www.performancehorizon.com (required)
+ website_type: 9 (required)
+ website_vertical: 10 (required)
+ description: Demo Publisher website - FIXME:null
+ website_country (Country)
+ website_name - FIXME:null

## Address (object)
+ address1: Gardegasse 11 (required) - 1st line of the address
+ address2: Top 7 - 2nd line of the address FIXME:null
+ address3: London - 3rd line of the address FIXME:null
+ address4 - 4th line of the address FIXME:null
+ country (Country) (required) - Country of the address
+ postcode: `A-101` (required) - Postcode/Zipcode attached to the address

## Phone (object)
+ phone: 01595725007 (required) - Primary contact telephone number
+ phone_area - FIXME:null

## Signup IP (object)
+ signup_ip: 178.23.129.160 (required)

## Created (object)
+ created: `2011-08-20 17:56:23` (required)

## Yes Or No (enum)
+ y - yes
+ n - no
+ Sample: y

## Status (enum)
+ a - Approved
+ p - Pending
+ r - Rejected
+ Sample: a

## Country (enum)
+ GB - Great Britain
+ JP - Japan
+ Sample: GB

## Locale (enum)
+ en - English
+ Sample: en

## Timezone (enum)
+ Australia/Sydney
+ Sample: Australia/Sydney

## Currency (enum)
+ GBP - Great Britain Pounds
+ Sample: GBP

## Network Wrapper (object)
+ network (Network)

## Publisher Wrapper (object)
+ publisher (Publisher)

## Publisher Website Wrapper (object)
+ website (Publisher Website)
