FORMAT: 1A
HOST: https://api.performancehorizon.com

# Performance Horizon Internal API

# Group Job

## Job [/job/{job_id}]

+ Attributes (object)
    + job_id: 111111l470 - ID of the job
    + created_at: `2016-04-07 04:21:51`
    + completed_at: `2016-04-07 04:21:52`
    + created_by: 300621 - ID of the user who created the job
    + created_by_uri
    + status (enum)
        + complete
    + percentage_complete: 100 (number)
    + reference
    + response_within_retention: true (boolean)
    + estimated_completion
    + time_elapsed

### View a Single Job [GET]

+ Parameters
    + job_id: 111111l470 - ID of the job

+ Response 200 (application/json)
    + Attributes (Job Wrapper)

### List all Jobs [GET /job]

Return the details of all Jobs created by the authenticated User.

+ Response 200 (application/json)
    + Attributes
        + jobs (array[Job Wrapper])

# Group Campaign Feed

## Campaign Feed [/campaign/{campaign_id}/feed]

+ Parameters
    + campaign_id: 300389 - ID of the campaign

+ Attributes (object)
    + feed_id: 1111l13 - ID of the campaign feed
    + Include Campaign Feed Base
    + updated: 1378980455 (number)
    + last_processed: 1378980455 (number)

### List all Campaign Feeds [GET]

+ Response 200 (application/json)
    + Attributes
        + feeds (array[Campaign Feed Wrapper])

### Create a Campaign Feed [POST]

+ Request (application/json)
    + Attributes
        + feeds (array[Campaign Feed Base])

+ Response 200 (application/json)
    + Attributes
        + feeds (array[Campaign Feed Wrapper])

### Update a Campaign Feed [PUT]

+ Request (application/json)
    + Attributes
        + feeds (array)
            + (Campaign Feed Base)
                + feed_id: 300092 - ID of the campaign feed

+ Response 200 (application/json)
    + Attributes
        + feeds (array[Campaign Feed Wrapper])

# Group Granular Reporting

## List all Clicks attached to Campaign [GET /reporting/report_advertiser/campaign/{campaign_id}/click?{start_date,end_date}]

Return the details of all Clicks attached to the Campaign within the requested time period.

+ Parameters
    + campaign_id: 300389 - ID of the campaign
    + start_date: `2016-02-30T05:15:32Z`
    + end_date: `2016-03-10T19:02:35Z`

+ Response 200 (application/json)
    + Attributes
        + unique_click_count: 28 (number)
        + start_date_time: `2015-03-21 16:29:46`
        + end_date_time: `2015-07-02 19:43:51`
        + clicks (array)
            + (object)
                + click (Click)
                    + advertiser_reference

## List all Conversions attached to Campaign [GET /reporting/report_advertiser/campaign/{campaign_id}/conversion?{start_date,end_date}]

Return the details of all Conversions attached to the Campaign within the requested time period.

+ Parameters
    + campaign_id: 300389 - ID of the campaign
    + start_date: `2016-02-30T05:15:32Z`
    + end_date: `2016-03-10T19:02:35Z`

+ Response 200 (application/json)
    + Attributes
        + total_conversion_count
            + GBP: 97 (number)
        + total_commission_value
            + GBP: 39417.7684 (number)
        + total_publisher_commission
            + GBP: 35804.7927 (number)
        + total_value
            + GBP: 186166.28 (number)
        + conversions (array)
            + (object)
                + conversion_data (Conversion)
                    + click (Click)
                        + advertiser_reference

## List all Clicks generated by Publisher [GET /reporting/report_publisher/publisher/{publisher_id}/click?{start_date,end_date}]

Return the details of all Clicks generated by the Publisher within the requested time period.

+ Parameters
    + publisher_id: 300254 - ID of the publisher
    + start_date: `2016-02-30T05:15:32Z`
    + end_date: `2016-03-10T19:02:35Z`

+ Response 200 (application/json)
    + Attributes
        + unique_click_count: 28 (number)
        + start_date_time: `2015-03-21 16:29:46`
        + end_date_time: `2015-07-02 19:43:51`
        + clicks (array)
            + (object)
                + click (Click)
                    + publisher_reference

## List all Conversions generated by Publisher [GET /reporting/report_publisher/publisher/{publisher_id}/conversion?{start_date,end_date}]

Return the details of all Conversions generated by the Publisher within the requested time period.

+ Parameters
    + publisher_id: 300254 - ID of the publisher
    + start_date: `2016-02-30T05:15:32Z`
    + end_date: `2016-03-10T19:02:35Z`

+ Response 200 (application/json)
    + Attributes
        + total_conversion_count
            + GBP: 97 (number)
        + total_commission_value
            + GBP: 39417.7684 (number)
        + total_publisher_commission
            + GBP: 35804.7927 (number)
        + total_value
            + GBP: 186166.28 (number)
        + conversions (array)
            + (object)
                + conversion_data (Conversion)
                    + click (Click)
                        + publisher_reference

# Group Aggregated Reporting

## Aggregrate Advertiser [GET /reporting/report_advertiser/campaign/{campaign_id}/overview/{pivot}?{start_date,end_date}]

Return the aggregation stats for the requested `pivot` within the requested time period.

+ Parameters
    + campaign_id: 300389 - ID of the campaign
    + pivot (enum[string])
        + primary - All Publishers                                        
        + adref - All advertiser references referenced through tracking 
        + product - All tracked item categories                           
        + country - All countries detected from tracking events           
        + type - The type of each Conversion                           
        + creative - Stats related to all active Creative                  
        + agent - The type of device used                               
        + custref - Optional customer identifiers referenced in tracking  
        + self - Totals for the Campaign                              
    + start_date: `2016-02-30T05:15:32Z`
    + end_date: `2016-03-10T19:02:35Z`

+ Response 200 (application/json)
    + Attributes

## Aggregrate Publisher [GET /reporting/report_publisher/publisher/{publisher_id}/overview/{pivot}?{start_date,end_date}]

Return the aggregation stats for the requested `pivot` within the requested time period.

+ Parameters
    + publisher_id: 300254 - ID of the publisher
    + pivot (enum[string])
        + primary - All Campaigns                                        
        + pubref - All publisher references referenced through tracking
        + product - All tracked item categories                           
        + country - All countries detected from tracking events           
        + type - The type of each Conversion                           
        + creative - Stats related to all active Creative                  
        + agent - The type of device used                               
        + custref - Optional customer identifiers referenced in tracking  
        + self - Totals for the Campaign                              
    + start_date: `2016-02-30T05:15:32Z`
    + end_date: `2016-03-10T19:02:35Z`

+ Response 200 (application/json)
    + Attributes

# Group Export Reporting

# Group Meta

## List all Meta attributes for Campaign [GET /campaign/{campaign_id}/meta]

+ Parameters
    + campaign_id: 300389 - ID of the campaign

+ Response 200 (application/json)
    + Attributes
        + campaign
            + campaign_id: 300389 - ID of the campaign
            + meta
                + currencies (array[Currency])
                + meta_conversion (array)
                + meta_item (array)

## List all Meta attributes for Publisher [GET /user/publisher/{publisher_id}/meta]

+ Parameters
    + publisher_id: 300254 - ID of the publisher

+ Response 200 (application/json)
    + Attributes
        + publisher
            + publisher_id: 300254 - ID of the publisher
            + meta
                + currencies (array[Currency])
                + meta_conversion (array)
                + meta_item (array)

## List all Meta attributes for Campaign Group [GET /user/advertiser/{advertiser_id}/campaign_group/{campaign_group_id}/meta]

+ Parameters
    + advertiser_id: 300309 - ID of the advertiser
    + campaign_group_id: 300389 - ID of the campaign group

+ Response 200 (application/json)
    + Attributes
        + 
            + meta
                + currencies (array[Currency])
                + meta_conversion (array)
                + meta_item (array)

# Group Network Publisher

# Group Publisher Creative

# Group Campaign Creative

# Group Creative Tags

# Group Campaign Bonus

## Campaign Bonus [/user/advertiser/{advertiser_id}/campaign/{campaign_id}/bonus]

+ Parameters
    + advertiser_id: 300309 - ID of the advertiser
    + campaign_id: 300389 - ID of the campaign

+ Attributes

### Create a Bonus Conversion [POST]

+ Request (application/json)
    + Attributes
        + conversion (array)
            + (object)
                + publisher_id: 300254 (required) - ID of the publisher
                + commission (number, required)
                + value (number, required)

+ Response 200 (application/json)
    + Attributes

# Data Structures

## Campaign Feed Base (object)
+ name: Sample Feed (required)
+ active (YesOrNo)
+ location (required)
+ location_local
+ fetch_frequency: 3600 (number)
+ filesize: 0 (number)
+ dynamic: 0 (number)
+ action

## Click (object)
+ click_id: 111111l100057
+ cookie_id: 111111l38040
+ campaign_id: 300389 - ID of the campaign
+ publisher_id: 300254 - ID of the publisher
+ publisher_name: Demo
+ type
+ status
+ set_time: `2015-03-28 11:08:52`
+ set_ip: 127.0.0.1
+ last_used: `2015-03-28 11:08:52`
+ last_ip: 127.0.0.1
+ referer
+ country (Country)
+ creative_id: 0 (number)
+ creative_type: 0 (number)
+ specific_creative_id: 0 (number)
+ ref_device_id: 1 (number)
+ ref_traffic_source_id: 1 (number)

## Conversion (object)
+ conversion_id: 111111l726240
+ cookie_id: 111111l38040
+ campaign_id: 300389 - ID of the campaign
+ publisher_id: 300254 - ID of the publisher
+ publisher_name: Demo
+ campaign_title: Demo Campaign
+ click (Click)
+ conversion_time: `2016-04-10 13:08:15`,
+ last_modified: `2016-04-10 13:08:16`
+ currency (Currency)
+ currency_original (Currency)
+ currency_conversion_rate
+ customer_type
+ conversion_type: 1 (number)
+ conversion_reference: `AUTO-570a968f38b55`,
+ advertiser_reference
+ customer_reference
+ source_referer
+ referer_ip: 127.0.0.1
+ user_agent: Mozilla
+ country (Country)
+ creative_id: 0 (number)
+ creative_type: 0 (number)
+ specific_creative_id: 0 (number)
+ ref_device_id: 1 (number)
+ ref_traffic_source_id: 1 (number)
+ ref_partnership_model_id: 2 (number)
+ ref_conversion_metric_id: 2 (number)
+ ref_user_context_id: 3 (number)
+ was_disputed: false (boolean)
+ conversion_lag: 33 (number)
+ conversion_items (array[Conversion Item])
+ conversion_value
    + conversion_value_id: 111111l726195
    + conversion_status (Conversion Status)
    + value: 915.26 (number)
    + commission: 2013.572 (number)
    + publisher_commission: 1830.52 (number)

## Conversion Item
+ conversion_item_id: 111111l1107235 - ID of the conversion item
+ sku: 855779
+ category: Promotion
+ item_value: 915.26 (number)
+ item_commission: 2013.572 (number)
+ item_publisher_commission: 1830.52 (number)
+ item_status (Conversion Status)
+ invoice_id
+ last_update: `2016-04-10 13:08:16`
+ item_status_id: 1 (number)
+ reject_reason
+ voucher_codes (array)

## YesOrNo (enum)
+ y - yes
+ n - no

### Sample
+ y

## Country (enum)
+ GB - Great Britain
+ JP - Japan

### Sample
+ GB

## Currency (enum)
+ GBP - Great Britain Pounds

### Sample
+ GBP

## Conversion Status (enum)
+ pending
+ accepted
+ rejected

### Sample
+ pending

## Job Wrapper (object)
+ job (Job)

## Campaign Feed Wrapper (object)
+ feed (Campaign Feed)
