FORMAT: 1A
HOST: https://api.performancehorizon.com

# Performance Horizon API
This is the full external API documentation for the [PH](http://performancehorizon.com) API. Every feature exposed to
our clients through our [Web App](https://phgconsole.performancehorizon.com) can be consumed programmatically through
the API. This API documentation is written in [api blueprint](https://apiblueprint.org/) which can be read by humans
and machines.

The documentation is interactive; calls can be made to all documented endpoints within the browser
without the need to write any code. For devs, there are many tools available to consume the documentation, for more
information check out the [tools section](https://apiblueprint.org/tools.html).

Finally, our API docs are open source. We would welcome any corrections, updates or bug fixes - to do this, please
submit a pull request on our [Github project page](https://github.com/PerformanceHorizonGroup/apidocs).

:[](intro.apib)

:[](user.apib)

:[](network.apib)

:[](publisher.apib)

:[](publisher_website.apib)

:[](publisher_database.apib)

:[](advertiser.apib)

:[](campaign.apib)

:[](commission.apib)

:[](commission_group.apib)

:[](voucher_code.apib)

:[](participating_publishers.apib)

:[](publisher_campaign.apib)

:[](invoice.apib)

:[](selfbill.apib)

:[](campaign_conversion.apib)

:[](campaign_tracking.apib)

:[](job.apib)

:[](granular_reporting.apib)

:[](aggregated_reporting.apib)

:[](export_reporting.apib)

:[](network_publisher.apib)

:[](campaign_creative.apib)

:[](publisher_creative.apib)

:[](creative_tags.apib)

:[](campaign_bonus.apib)

:[](reference.apib)

:[](meta.apib)

:[](campaign_feed.apib)

:[](alert.apib)

:[](publisher_transaction_query.apib)

# Data Structures

:[](../data/common.apib)

:[](../data/account.apib)

:[](../data/advertiser.apib)

:[](../data/campaign.apib)

:[](../data/commission.apib)

:[](../data/creative.apib)

:[](../data/publisher.apib)

:[](../data/reporting.apib)

:[](../data/user.apib)

:[](../data/voucher.apib)

:[](../data/alert.apib)

:[](../data/transaction_query.apib)

:[](../data/wrappers.apib)
