# Group Campaign Conversion

An Advertiser must approve or reject all conversion events that occur on their Campaigns. A conversion can have one or more
conversion items, and it is the items which must be updated before they can be Invoiced or ignored. It is possible to
update the status of items individually, or all items within a conversion can be referenced at the same time.
Due to the high volume of processing that can happen on this endpoint, it is Job enabled.

### Update Conversion Events [POST /campaign/{campaign_id}/conversion]

A Conversion update can be actioned against one of 3 references. The relevant reference must be passed, with its
associated id and status. Bulk operations are sent within a `conversions` array. An optional `reject_reason` can
be sent with references that are set to the `rejected` status.

+ Parameters
    + campaign_id: 10l176 - ID of the campaign

+ Request (application/json; charset=utf-8)
    + Attributes
        + conversions (array)
            + (object)
                + One Of
                    + conversion_id - The unique identifier for a conversion, which will affect all items attached to it
                    + conversion_reference_id - The Advertiser's own reference for the conversion, which will affect all items attached to it
                    + conversion_item_id - The unique identifier for an individual item, this only affects its own status
                + status (enum)
                    + approved
                    + pending
                    + rejected
                + reject_reason

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Job Wrapper)
