## Publisher Update (object)
+ promotional_method: 9 (number, required)
+ description: Top performance (string, optional, nullable) - Description of the publisher

## Publisher Base (object)
+ account_name: publisher123 (required)
+ vertical_name: Other (string, optional)
+ vertical: 10 (number, required)
+ promotional_method_name: Portal (string, optional)
+ promotional_method: 10 (number, required)
+ vat_number: 974997534 (number, optional, nullable)
+ uk_vat_registered (YesOrNo)
+ description (string, optional, nullable) - Description of the publisher
+ company_name: Demo Publisher
+ company_division (string, optional, nullable)
+ operating_country (Country)
+ Include Time Info
+ default_currency (Currency)
+ Include Phone
+ contact_name: Pete Cheyne
+ contact_email: demo@performancehorizon.com
+ contact_locale (Locale)
+ im_provider: Skype  (string, optional, nullable)
+ im_username: elisangis  (string, optional, nullable)
+ Include Signup IP
+ is_lead_user (YesOrNo, nullable)
+ is_foreign_network (YesOrNo, nullable)

## Publisher Website Base (object)
+ website_url: http://www.performancehorizon.com (required)
+ description: Demo Publisher website
+ website_type: 9 (number, required)
+ website_vertical: 10 (number, required)
+ website_country (Country)
+ website_name (nullable)
+ website_vertical_name: Technical
+ website_type_name: PPC
+ active (YesOrNo)

## Publisher Website (object)
+ website_id: 11l18694 - ID of the publisher website
+ publisher_id: 1l1007802 - ID of the publisher the website belongs to
+ Include Publisher Website Base

## Publisher Database Base (object)
+ database_name: PHG Test Database (required)
+ creation_method: Email (required)
+ size: 53000 (number, required)
+ male: 50 (number)
+ female: 50 (number)
+ min_age: 25 (number)
+ max_age: 77 (number)

## Publisher Database (object)
+ database_id: 111111l300347 - ID of the publisher database
+ publisher_id: 1l1007802 - ID of the publisher the database belongs to
+ Include Publisher Database Base

## Publisher (object)
+ publisher_id: 1l1007802 - ID of the publisher
+ Include Publisher Base
+ network_status (Status)
+ network_id: 1l1000003 - ID of the network this publisher belongs to
+ network_notes (string, optional, nullable)
+ campaign_select (string, optional, nullable)
+ is_affiliate_user (YesOrNo)
+ foreign_identifier (string, optional, nullable)
+ reporting_identifier (string, optional, nullable)
+ gst_registered (string, optional, nullable)
+ us_tax_state (string, optional, nullable)
+ abn (string, optional, nullable)
+ websites (array[Publisher Website])
+ databases (array[Publisher Database])
+ legal_entity (Country)

## Phone (object)
+ phone: 01595725007 (required) - Primary contact telephone number
+ phone_area: +44 (nullable) - Phone prefix to declare country or region

## Signup IP (object)
+ signup_ip: 178.23.129.160 (required)

## Time Info (object)
+ reporting_timezone (Timezones)
+ week_start: Monday

## Time Range (object)
+ start_date_time: `2013-08-31 15:00:00` (string, optional, nullable)
+ end_date_time: `2013-09-30 15:00:00` (string, optional, nullable)

## Status (enum)
+ a - Approved
+ p - Pending
+ r - Rejected
+ n

### Sample
+ a

## Job (object)
+ job_id: 111111l470 - ID of the job
+ completed_at: `2016-04-07 04:21:52` (string, optional, nullable)
+ Include Created
+ created_by_uri
+ status (enum)
    + complete
    + created
    + active
+ percentage_complete: 100 (number)
+ reference (nullable)
+ response_within_retention: true (boolean)
+ estimated_completion (nullable)
+ time_elapsed (number)
+ Include Hypermedia

## Created (object)
+ created_at: `2016-04-07 04:21:51`
+ created_by: 300621 - ID of the user who created the job

## YesOrNo (enum)
+ y - yes
+ n - no

### Sample
+ y

## Country (enum)
+ GB - Great Britain
+ JP - Japan
+ NL - Netherlands

### Sample
+ GB

## Locale (enum)
+ en - English

### Sample
+ en

## Timezones (enum)
+ Australia/Sydney
+ UTC
+ Europe/London
+ CET
+ GMT

### Sample
+ Australia/Sydney

## Currency (enum)
+ GBP - Great Britain Pounds
+ USD - United States Dollars
+ EUR - Euros
+ JPY - Japanese Yen

### Sample
+ GBP

## Publisher Wrapper (object)
+ publisher (Publisher)

## Job Wrapper (object)
+ job (Job)

## Hypermedia (object)
+ response: /job/111111l1177306/response.json (string, optional, nullable) - The raw response
+ update: /job/111111l1177306.json (string, optional, nullable) - The update URI

## Publisher Feed Base (object)
+ campaign_feeds_id: `1011l10`
+ name: `UK Destinations` - The name of the product feed
+ filename: `uk_destinations.csv`
+ location: `http://www.performancehorizon.com/` - Where the file is located
+ updated: 1432228514 (number)
+ campaign_id: `10l176`
+ title: `SportBetting` - The name of the campaign
+ creative_id: `300441`
+ location_compressed: `http://www.performancehorizon.com/` - Where the compressed file is located
+ filesize: 581427 (number)
+ filesize_compressed: 27691 (number)
+ last_processed: 1432235983 (number)

## Advertiser Conversion Wrapper (object)
+ total_conversion_count (object)
    + GBP: 97 (number)
+ total_commission_value (object)
    + GBP: 39417.7684 (number)
+ total_publisher_commission (object)
    + GBP: 35804.7927 (number)
+ total_value (object)
    + GBP: 186166.28 (number)
+ conversions (array)
    + (object)
        + conversion_data (Conversion)
            + click (Click)
                + advertiser_reference (string)