# Group Filter Sets

## Report Filter Sets [/report/filter_sets/{filter_set_id}]

Filter Sets can exist in two different scopes. The first one is for advertiser, and is defined by user and campaign; in that case, a campaign_id parameter is needed for any request. The second one is for publisher, and is defined by user and publisher; in that case, a publisher_id parameter is needed for any request.

Inasmuch as campaign_id and publisher_id are used to discriminate one of the two scope types, these parameters can not be used at the same time.

### List all filter sets [GET /report/filter_sets]

+ Request (application/json; charset=utf-8)
    + Attributes
        + campaign_id: 7 (string, required) - Id of the campaign (Advertiser Scope)
        + publisher_id: 7 (string, required) - Id of the publisher (Publisher Scope)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (object)
        + count: 5 (number) - Number of Filter Sets recovered
        + execution_time: `0.23640 seconds`
        + filter_sets (array[Filter Set]) - Recovered Filter Sets list
        + errors (array) - Empty error list

### Get a filter set [GET]

+ Parameters
    + filter_set_id: 38 (string, required) - Id of the filter set

+ Request (application/json; charset=utf-8)
    + Attributes
        + campaign_id: 7 (string, required) - Id of the campaign (Advertiser Scope)
        + publisher_id: 7 (string, required) - Id of the publisher (Publisher Scope)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + count: 1 (number) - Number of Filter Sets recovered
        + execution_time: `0.23640 seconds`
        + filter_sets (array[Filter Set]) - List with the recovered Filter Set
        + errors (array) - Empty error list

### Create a filter set [POST /report/filter_sets]

+ Request (application/json; charset=utf-8)
    + Attributes
        + name: `My lovely filters set` (string, required)
        + is_default: false (boolean, optional)
        + data: (string, required) - Must be a valid JSON string
        + campaign_id: 7 (string, required) - Id of the campaign (Advertiser Scope)
        + publisher_id: 7 (string, required) - Id of the publisher (Publisher Scope)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + count: 1 (number) - Number of Filter Sets created
        + execution_time: `0.23640 seconds`
        + filter_sets (array[Filter Set]) - Created Filter Sets list
        + errors (array) - Empty error list

+ Validation Rules
    + Filter Set names must be unique for the same scope (user and campaign).
    + Filter Set names must be under 256 characters.
    + Filter Set names must not be numeric. You can add numbers as part of a text string but not on their own.
    + Filter Set data must be a valid JSON string.
    + Filter Set data must be under 8192 characters.

### Update a filter set [PUT]

+ Parameters
    + filter_set_id: 38 (string, required) - Id of the filter set

+ Request (application/json; charset=utf-8)
    + Attributes
        + name: `My new name` (string, optional)
        + is_default: false (boolean, optional)
        + data: (string, optional) - Must be a valid JSON string
        + campaign_id: 7 (string, required) - Id of the campaign (Advertiser Scope)
        + publisher_id: 7 (string, required) - Id of the publisher (Publisher Scope)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + count: 1 (number) - Number of Filter Sets updated
        + execution_time: `0.23640 seconds`
        + filter_sets (array[Filter Set]) - Updated Filter Sets list
        + errors (array) - Empty error list

+ Validation Rules
    + Filter Set names must be unique for the same scope (user and campaign).
    + Filter Set names must be under 256 characters.
    + Filter Set names must not be numeric. You can add numbers as part of a text string but not on their own.
    + Filter Set data must be a valid JSON string.
    + Filter Set data must be under 8192 characters.

### Delete a filter set [DELETE]

+ Parameters
    + filter_set_id: 38 (string, required) - Id of the filter set

+ Request (application/json; charset=utf-8)
    + Attributes
        + campaign_id: 7 (string, required) - Id of the campaign (Advertiser Scope)
        + publisher_id: 7 (string, required) - Id of the publisher (Publisher Scope)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + count: 1 (number) - Number of Filter Sets deleted
        + execution_time: `0.23640 seconds`
        + filter_sets (array[Filter Set]) - Deleted Filter Sets list
        + errors (array) - Empty error list
