# Group Granular Advertiser Reporting

The granular reporting endpoints list all Clicks or Conversions related to a campaign individually. Due to the volume of data,
these result sets are Paginated.

## Clicks [/reporting/report_advertiser/campaign/{campaign_id}/click{?start_date,end_date}]

### List All Clicks [GET]

Return the details of all Clicks attached to the Campaign within the requested time period.

+ Parameters
    + campaign_id: 10l176 - ID of the campaign
    + start_date: `2016-02-30T05:15:32Z` (required)
    + end_date: `2016-03-10T19:02:35Z` (required)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Advertiser Click Wrapper)

## Conversions [/reporting/report_advertiser/campaign/{campaign_id}/conversion{?start_date,end_date}]

### List All Conversions [GET]

Return the details of all Conversions attached to the Campaign within the requested time period.

+ Parameters
    + campaign_id: 10l176 - ID of the campaign
    + start_date: `2016-02-30T05:15:32Z` (required)
    + end_date: `2016-03-10T19:02:35Z` (required)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Advertiser Conversion Wrapper)

### List All Conversions using Contextual Range [GET /reporting/report_advertiser/campaign/{campaign_id}/conversion{?text_date}]

Return the details of all Conversions attached to the Campaign within the requested time period provided in contextual format.

+ Parameters
    + campaign_id: 10l176 - ID of the campaign
    + text_date: last+45+days (required, enum[string]) - A relative date search using natural language
        + this hour
        + last hour
        + today
        + yesterday
        + this week
        + last week
        + this month
        + last month
        + this year
        + last year
        + last n days - Replace "n" with the numeric range

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Advertiser Conversion Wrapper)

# Group Granular Publisher Reporting

The granular reporting endpoints list all Clicks or Conversions related to an individual publisher.
Due to the volume of data, these result sets are Paginated.

## Clicks [/reporting/report_publisher/publisher/{publisher_id}/click{?start_date,end_date}]

### List All Clicks [GET]

Return the details of all Clicks generated by the Publisher within the requested time period.

+ Parameters
    + publisher_id: 1l1007802 - ID of the publisher
    + start_date: `2016-02-30T05:15:32Z` (required)
    + end_date: `2016-03-10T19:02:35Z` (required)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Publisher Click Wrapper)

## Conversions [/reporting/report_publisher/publisher/{publisher_id}/conversion{?start_date,end_date}]

## List All Conversions [GET]

Return the details of all Conversions generated by the Publisher within the requested time period.

+ Parameters
    + publisher_id: 1l1007802 - ID of the publisher
    + start_date: `2016-02-30T05:15:32Z` (required)
    + end_date: `2016-03-10T19:02:35Z` (required)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Publisher Conversion Wrapper)

### List All Conversions using Contextual Range [GET /reporting/report_publisher/publisher/{publisher_id}/conversion{?text_date}]

Return the details of all Conversions attached to the Campaign within the requested time period provided in contextual format.

+ Parameters
    + publisher_id: 1l1007802 - ID of the publisher
    + text_date: last+45+days (required, enum[string]) - A relative date search using natural language
        + this hour
        + last hour
        + today
        + yesterday
        + this week
        + last week
        + this month
        + last month
        + this year
        + last year
        + last n days - Replace "n" with the numeric range

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Publisher Conversion Wrapper)
