# Group Granular Reporting

The granular reporting endpoints list all Clicks or Conversions individually. Due to the volume of data,
these result sets are Paginated.

## List all Clicks attached to Campaign [GET /reporting/report_advertiser/campaign/{campaign_id}/click{?start_date,end_date}]

Return the details of all Clicks attached to the Campaign within the requested time period.

+ Parameters
    + campaign_id: 10l176 - ID of the campaign
    + start_date: `2016-02-30T05:15:32Z` (required)
    + end_date: `2016-03-10T19:02:35Z` (required)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + unique_click_count: 28 (number)
        + start_date_time: `2016-02-30 05:15:32`
        + end_date_time: `2016-03-10 19:02:35`
        + clicks (array)
            + (object)
                + click (Click)
                    + advertiser_reference

## List all Conversions attached to Campaign [GET /reporting/report_advertiser/campaign/{campaign_id}/conversion{?start_date,end_date}]

Return the details of all Conversions attached to the Campaign within the requested time period.

+ Parameters
    + campaign_id: 10l176 - ID of the campaign
    + start_date: `2016-02-30T05:15:32Z` (required)
    + end_date: `2016-03-10T19:02:35Z` (required)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + total_conversion_count
            + GBP: 97 (number)
        + total_commission_value
            + GBP: 39417.7684 (number)
        + total_publisher_commission
            + GBP: 35804.7927 (number)
        + total_value
            + GBP: 186166.28 (number)
        + conversions (array)
            + (object)
                + conversion_data (Conversion)
                    + click (Click)
                        + advertiser_reference

## List all Clicks generated by Publisher [GET /reporting/report_publisher/publisher/{publisher_id}/click{?start_date,end_date}]

Return the details of all Clicks generated by the Publisher within the requested time period.

+ Parameters
    + publisher_id: 1l1007802 - ID of the publisher
    + start_date: `2016-02-30T05:15:32Z` (required)
    + end_date: `2016-03-10T19:02:35Z` (required)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + unique_click_count: 28 (number)
        + start_date_time: `2016-02-30 05:15:32`
        + end_date_time: `2016-03-10 19:02:35`
        + clicks (array)
            + (object)
                + click (Click)
                    + publisher_reference

## List all Conversions generated by Publisher [GET /reporting/report_publisher/publisher/{publisher_id}/conversion{?start_date,end_date}]

Return the details of all Conversions generated by the Publisher within the requested time period.

+ Parameters
    + publisher_id: 1l1007802 - ID of the publisher
    + start_date: `2016-02-30T05:15:32Z` (required)
    + end_date: `2016-03-10T19:02:35Z` (required)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + total_conversion_count
            + GBP: 97 (number)
        + total_commission_value
            + GBP: 39417.7684 (number)
        + total_publisher_commission
            + GBP: 35804.7927 (number)
        + total_value
            + GBP: 186166.28 (number)
        + conversions (array)
            + (object)
                + conversion_data (Conversion)
                    + click (Click)
                        + publisher_reference
