FORMAT: 1A
HOST: https://api.performancehorizon.com

# Performance Horizon Internal API

The internal documentation is a collection of reserved endpoints which are meant for internal use or they expose
functionality which can have a dramatic impact.

# Group Meta

Based on all tracked events, a real-time cache of currencies and non standard conversion and conversion item
attributes are kept for all Campaigns and Publishers. This endpoint can be used to determine what non standard
data might appear in reports/exports and is also useful when building an external app which will display Conversion data.

## List all Meta attributes for Campaign [GET /campaign/{campaign_id}/meta]

View all unique Meta attributes for the Campaign.

+ Parameters
    + campaign_id: 300389 - ID of the campaign

+ Response 200 (application/json)
    + Attributes
        + campaign
            + campaign_id: 300389 - ID of the campaign
            + meta
                + currencies (array[Currency])
                + meta_conversion (array)
                + meta_item (array)

## List all Meta attributes for Publisher [GET /user/publisher/{publisher_id}/meta]

View all unique Meta attributes for the Publisher.

+ Parameters
    + publisher_id: 300254 - ID of the publisher

+ Response 200 (application/json)
    + Attributes
        + publisher
            + publisher_id: 300254 - ID of the publisher
            + meta
                + currencies (array[Currency])
                + meta_conversion (array)
                + meta_item (array)

## List all Meta attributes for Campaign Group [GET /user/advertiser/{advertiser_id}/campaign_group/{campaign_group_id}/meta]

View all unique Meta attributes for the Campaign Group.

+ Parameters
    + advertiser_id: 300309 - ID of the advertiser
    + campaign_group_id: 111111l1 - ID of the campaign group

+ Response 200 (application/json)
    + Attributes
        + campaign_group
            + campaign_group_id: 111111l1 - ID of the campaign group
            + meta
                + currencies (array[Currency])
                + meta_conversion (array)
                + meta_item (array)

# Group Campaign Feed

An Advertiser may want to offer a selection of product feeds to their Publishers on a specific Campaign.
When a Feed is created, it will be periodically downloaded and parsed for all Publishers who participate on the
Campaign to ensure their tracking links are inserted for all anchor links within the product feed.
Any text based file format is supported.

## Campaign Feed [/campaign/{campaign_id}/feed]

+ Parameters
    + campaign_id: 300389 - ID of the campaign

+ Attributes (object)
    + feed_id: 1111l13 - ID of the campaign feed
    + Include Campaign Feed Base
    + updated: 1378980455 (number)
    + last_processed: 1378980455 (number)

### List all Campaign Feeds [GET]

Return the details of all Feeds attached to the Campaign.

+ Response 200 (application/json)
    + Attributes
        + feeds (array[Campaign Feed Wrapper])

### Create a Campaign Feed [POST]

Create one or more Feeds against the Campaign entity. Each Feed is sent as an array within a top level `feeds` array.

+ Request (application/json)
    + Attributes
        + feeds (array[Campaign Feed Base])

+ Response 200 (application/json)
    + Attributes
        + feeds (array[Campaign Feed Wrapper])

### Update a Campaign Feed [PUT]

Update one or more `feeds` against the Campaign entity. Each Feed is sent as an array within a top level `feeds`
array and must contain its associated `feed_id`.

+ Request (application/json)
    + Attributes
        + feeds (array)
            + (Campaign Feed Base)
                + feed_id: 300092 - ID of the campaign feed

+ Response 200 (application/json)
    + Attributes
        + feeds (array[Campaign Feed Wrapper])

# Data Structures

## Campaign Feed Base (object)
+ name: Sample Feed (required)
+ active (YesOrNo)
+ location (required)
+ location_local
+ fetch_frequency: 3600 (number)
+ filesize: 0 (number)
+ dynamic: 0 (number)
+ action

:[](common.apib)

## Campaign Feed Wrapper (object)
+ feed (Campaign Feed)
