# Group Meta

Based on all tracked events, a real-time cache of currencies and non standard conversion and conversion item
attributes are kept for all Campaigns and Publishers. This endpoint can be used to determine what non standard
data might appear in reports/exports and is also useful when building an external app which will display Conversion data.

## List all Meta attributes for Campaign [GET /campaign/{campaign_id}/meta]

View all unique Meta attributes for the Campaign.

+ Parameters
    + campaign_id: 10l176 - ID of the campaign

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + campaign
            + campaign_id: 10l176 - ID of the campaign
            + meta
                + currencies (array[Currency])
                + meta_conversion (array)
                + meta_item (array)

## List all Meta attributes for Publisher [GET /user/publisher/{publisher_id}/meta]

View all unique Meta attributes for the Publisher.

+ Parameters
    + publisher_id: 1l1007802 - ID of the publisher

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + publisher
            + publisher_id: 1l1007802 - ID of the publisher
            + meta
                + currencies (array[Currency])
                + meta_conversion (array)
                + meta_item (array)

## List all Meta attributes for Campaign Group [GET /user/advertiser/{advertiser_id}/campaign_group/{campaign_group_id}/meta]

View all unique Meta attributes for the Campaign Group.

+ Parameters
    + advertiser_id: 10l110 - ID of the advertiser
    + campaign_group_id: 62 - ID of the campaign group

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + campaign_group
            + campaign_group_id: 62 (number) - ID of the campaign group
            + meta
                + currencies (array[Currency])
                + meta_conversion (array)
                + meta_item (array)

## List all Reporting Meta Whitelist Keys for a Campaign [GET /campaign/{campaign_id}/reporting/meta/whitelist]

View all keys that are whitelisted and that are permitted to be used as part of the Reporting on Meta functionality.

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + whitelist
            + 0
                + type: conversion - Conversion level Whitelist Keys
                + keys
                    + 0
                        + key: key_name_1
                    + 1
                        + key: key_name_2
            + 1
                + type: item - Item level Whitelist Keys
                + keys
                    + 0
                        + key: key_name_3
                    + 1
                        + key: key_name_4