# Partner Marketplace

The Partner Marketplace allows advertisers to find potential publishers to invite to their networks/campaigns.

## Publisher Discovery [/v2/networks/{network_id}/marketplace/discovery/publishers]

+ Parameters
    + network_id: 1l1007802 - ID of the network