# Group Partner Marketplace

The Partner Marketplace allows advertisers to find potential publishers to invite to their networks/campaigns.

## Publisher Discovery [/v2/networks/{network_id}/marketplace/discovery/publishers{?limit,offset}]

+ Parameters
    + network_id: 1l1007802 - ID of the network
    + limit: 100 (number, optional)
    + offset: 0 (number, optional)


### List all Invitable Publishers [GET]

List all Publishers who are illigible to join the network.

+ Response 200 (application/json; charset=utf-8)
    + Attributes (marketplace_partner_discovery, fixed-type)



## Publisher Invitations [/v2/networks/{network_id}/marketplace/discovery/invitations]

+ Parameters
    + network_id: 1l1007802 - ID of the network
   

### Create Invitations  [POST]

Invite Publishers to Campaigns on the network.

+ Request (application/json; charset=utf-8)
    + Attributes 
        + publisher_invitations (array, fixed-type, required)
            + (marketplace_invitations_create_request)

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + execution_time: `0.98709 seconds` (string)
        + success_count: 6 (number)
        + failure_count: 0 (number)
  
+ Response 400 (application/json; charset=utf-8)
    + Attributes
        + execution_time: `0.98709 seconds` (string)
        + success_count: 0 (number)
        + failure_count: 1 (number)
        + failures (array, fixed-type)
            + (object)
                + index: 0 (number) - array index in the request 
                + data (object)
                    + publisher_id (string)
                        + Sample: 100l1258
                    + campaign_id (string)
                        + Sample: 1011l423
                + errors (array, fixed-type)
                    + (object)
                        + type: validation_error (string)
                        + code: non_unique (string)
                        + message (string) 
                            + Sample: `Invitation for publisher_id '100l1258' and campaign_id '1011l423' already exists.`
 
+ Response 404 (application/json; charset=utf-8)
    + Attributes
        + error (object)
            + type: entity_not_found (string)
            + message (string)
                + Sample: `Network not found for id '1l1007555'`
