# Group Publisher Payment Locale

List of fields in Publisher payment page.

## Publisher Payment Locales [/user/publisher/{publisher_id}/payment_locale]

+ Parameters
    + publisher_id: 1l1007802 - ID of the publisher

### List all Payment details per locale [GET]

View all details per locale.

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + count: 0 (number)
        + execution_time: `2.25885 seconds`
        + payment_locale_details (array[Publisher Payment Locale])