# Group Publisher

A User can create one or more Publisher accounts. A User can also have access to one or more Publisher accounts - this
is determined by the User's permissions. A Network admin may choose to grant a User access to multiple entities
within their Network.

## Publishers [/user/publisher]

### List Publishers [GET]

One or more Publishers can reside on a Network. This endpoint will output a listing of all Publishers who have access
to the Network and the output is contextual based on the permissions of the User making the request to the endpoint.
A limited Publisher schema will be utilised for any Publisher that the User does not have appropriate permissions to view.

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + publishers (array[Publisher Wrapper])

### Create a Publisher [POST]

Create a new Publisher account attached to the authenticated User.

+ Request (application/json; charset=utf-8)
    + Attributes (Publisher Base)
        + account_name: newpublisher123 (required) - Unique advertiser account name
        + entity_id: 1 (required) - The relevant entity id
        + network_id: 1l1000003 (required) - The relevant network id
        + entity_terms_id: 252 (required) - The terms and conditions ID (ref_terms_and_conditions_locale_id) for the specified entity. See Reference Terms and Conditions for more information

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Publisher Wrapper)

## Publisher [/user/publisher/{publisher_id}]

+ Parameters
    + publisher_id: 1l1007802 - ID of the publisher

### Retreive Publisher [GET]

Outputs the specified publisher.

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Publisher Wrapper)

### Update Publisher [POST]

Update the specified Publisher.

+ Request (application/json; charset=utf-8)
    + Attributes (Publisher Update)
        + publisher_id: 1l1007802 - ID of the publisher

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Publisher Wrapper)
