# Group Report Views

## Report Views [/report/views/{report_view_id}]

### List all report views [GET]

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + (object)
            + report_view (Report View)

### Get a report view [GET]

+ Parameters
    + report_view_id: 38 (string, required) - Id of the report view

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + report_view (Report View)

### Create a report view [POST]

+ Request (application/json; charset=utf-8)
    + Attributes
        + name: `My lovely report view` (string, required)
        + default: false (boolean, optional)
        + view_settings: (string, required) - Must be a valid JSON string

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + report_view (Report View)

### Update a report view [PUT]

+ Parameters
    + report_view_id: 38 (string, required) - Id of the report view

+ Request (application/json; charset=utf-8)
    + Attributes
        + name: `My new name` (string, optional)
        + default: false (boolean, optional)
        + view_settings: (string, required) - Must be a valid JSON string

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + report_view (Report View)

### Delete a report view [DELETE]

+ Parameters
    + report_view_id: 38 (string, required) - Id of the report view

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + report_view (Report View)
