# Group Report Views

## Report Views [/reporting/views]

### List all report views [GET]

## Report View [/reporting/view/{report_view_id}]

### Get a report view [GET]

+ Parameters
    + report_view_id: 38 (string, required) - Id of the report view

+ Request (application/json; charset=utf-8)
    + Attributes

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + report_view (Report View)

### Create a report view [POST]

+ Request (application/json; charset=utf-8)
    + Attributes

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + report_view (Report View)

### Update a report view [PUT]

+ Parameters
    + report_view_id: 38 (string, required) - Id of the report view

+ Request (application/json; charset=utf-8)
    + Attributes

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + report_view (Report View)

### Delete a report view [DELETE]

+ Parameters
    + report_view_id: 38 (string, required) - Id of the report view

+ Request (application/json; charset=utf-8)
    + Attributes

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + report_view (Report View)
