# Group Reporting

## List all Reporting Meta Whitelist Keys for a Campaign [GET /campaign/{campaign_id}/reporting/meta/whitelist]

View all keys that are whitelisted and that are permitted to be used as part of the Reporting on Meta functionality.

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + whitelist (array)
            + (object)
                + type: conversion - Conversion level Whitelist Keys
                + keys (array)
                    + (object)
                        + key: key_name_1
                    + (object)
                        + key: key_name_2
            + (object)
                + type: item - Item level Whitelist Keys
                + keys (array)
                    + (object)
                        + key: key_name_3
                    + (object)
                        + key: key_name_4

## List all Reporting Meta Values for a Campaign [GET /campaign/{campaign_id}/reporting/meta/values]

Get all values for conversions / conversion-items meta keys in the meta key whitelist.

+ Parameters
    + campaign_id: 10l176 - ID of the campaign

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + conversion (array)
            + (object)
                + key: key_name_1
                + values: value 1.1, value 1.2, value 1.3 (array) - Value list for key_name_1
            + (object)
                + key: key_name_2
                + values: value 2.1, value 2.2, value 2.3 (array) - Value list for key_name_2
        + item (array)
            + (object)
                + key: key_name_3
                + values: value 3.1, value 3.2, value 3.3 (array) - Value list for key_name_3
            + (object)
                + key: key_name_4
                + values: value 4.1, value 4.2, value 4.3 (array) - Value list for key_name_4