# Group Reporting

## List all Reporting Meta Whitelist Keys for a Campaign [GET /campaign/{campaign_id}/reporting/meta/whitelist]

View all keys that are whitelisted and that are permitted to be used as part of the Reporting on Meta functionality.

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + whitelist (object) - Key list for Conversion level
            + conversion (array)
                + conversion_key_name_1
                + conversion_key_name_2
            + item (array) - Key list for Item level
                + item_key_name_1
                + item_key_name_2

## List all Reporting Meta Values for a Campaign [GET /campaign/{campaign_id}/reporting/meta/values]

Get all values for conversions / conversion-items meta keys in the meta key whitelist.

+ Parameters
    + campaign_id: 10l176 - ID of the campaign

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + meta_values (object)
            + conversion (object)
                + conversion_key_name_1 (array) - Value list for conversion_key_name_1
                    + value_1
                    + value_2
                    + value_3
            + item (object)
                + item_key_name_1 (array) - Value list for item_key_name_1
                    + value_1
                    + value_2
                    + value_3