# Group Terms and Conditions

Terms and conditions endpoint that returns terms and conditions that must be accepted by a publisher to join the network.

## Terms and Conditions [/reference/terms/{locale}/{country}/{network_id}]

Terms and conditions, with internationalisation, for a specific network, that must be accepted by publishers on sign up

+ Parameters
    + locale: en (enum[string]) - Specified locale
        + Members
            + bg
            + cs
            + da
            + de
            + de_at
            + en
            + en_au
            + en_ca
            + en_us
            + es
            + es_mx
            + el   
            + et
            + fi
            + fl
            + fr
            + fr_ca
            + hu
            + id
            + it
            + jp
            + ko
            + ko_kr
            + lt
            + lv
            + ms_my
            + mt
            + my
            + nl
            + no
            + pl
            + po
            + pt
            + pt_br
            + ro
            + ru
            + sg
            + sk
            + sl
            + sv
            + sv_se
            + th
            + tl
            + tr
            + vi
            + zh_cn
            + zh_hk
    + country: GB (enum[string]) - Specified ISO-2 country code
        + Members
            + AD
            + AE
            + AF
            + AG
            + AI
            + AL
            + AM
            + AO
            + AQ
            + AR
            + AS
            + AT
            + AU
            + AW
            + AX
            + AZ
            + BA
            + BB
            + BD
            + BE
            + BF
            + BG
            + BH
            + BI
            + BJ
            + BL
            + BM
            + BN
            + BO
            + BQ
            + BR
            + BS
            + BT
            + BV
            + BW
            + BY
            + BZ
            + CA
            + CC
            + CD
            + CF
            + CG
            + CH
            + CI
            + CK
            + CL
            + CM
            + CN
            + CO
            + CR
            + CU
            + CV
            + CW
            + CX
            + CY
            + CZ
            + DE
            + DJ
            + DK
            + DM
            + DO
            + DZ
            + EC
            + EE
            + EG
            + EH
            + ER
            + ES
            + ET
            + FI
            + FJ
            + FK
            + FM
            + FO
            + FR
            + GA
            + GB
            + GD
            + GE
            + GF
            + GG
            + GH
            + GI
            + GL
            + GM
            + GN
            + GP
            + GQ
            + GR
            + GS
            + GT
            + GU
            + GW
            + GY
            + HK
            + HM
            + HN
            + HR
            + HT
            + HU
            + ID
            + IE
            + IL
            + IM
            + IN
            + IO
            + IQ
            + IR
            + IS
            + IT
            + JE
            + JM
            + JO
            + JP
            + KE
            + KG
            + KH
            + KI
            + KM
            + KN
            + KP
            + KR
            + KW
            + KY
            + KZ
            + LA
            + LB
            + LC
            + LI
            + LK
            + LR
            + LS
            + LT
            + LU
            + LV
            + LY
            + MA
            + MC
            + MD
            + ME
            + MF
            + MG
            + MH
            + MK
            + ML
            + MM
            + MN
            + MO
            + MP
            + MQ
            + MR
            + MS
            + MT
            + MU
            + MV
            + MW
            + MX
            + MY
            + MZ
            + NA
            + NC
            + NE
            + NF
            + NG
            + NI
            + NL
            + NO
            + NP
            + NR
            + NU
            + NZ
            + OM
            + PA
            + PE
            + PF
            + PG
            + PH
            + PK
            + PL
            + PM
            + PN
            + PR
            + PS
            + PT
            + PW
            + PY
            + QA
            + RE
            + RO
            + RS
            + RU
            + RW
            + SA
            + SB
            + SC
            + SD
            + SE
            + SG
            + SH
            + SI
            + SJ
            + SK
            + SL
            + SM
            + SN
            + SO
            + SR
            + SS
            + ST
            + SV
            + SX
            + SY
            + SZ
            + TC
            + TD
            + TF
            + TG
            + TH
            + TJ
            + TK
            + TL
            + TM
            + TN
            + TO
            + TR
            + TT
            + TV
            + TW
            + TZ
            + UA
            + UG
            + UM
            + US
            + UY
            + UZ
            + VA
            + VC
            + VE
            + VG
            + VI
            + VN
            + VU
            + WF
            + WS
            + XK
            + YE
            + YT
            + ZA
            + ZM
            + ZW
    + network_id: 11l100 - ID of the network

### List all terms for a network [GET]

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + terms (array[Term Wrapper])