# Group Voucher Code

A Voucher references a coupon code, or voucher code which the Advertiser offers to their customers to usually
 perform a price discount at the end of the transaction. Specific rules can be set to defined Vouchers ensuring that
 only valid codes can be used and can also be restricted to specific Publishers.

## Voucher Codes [/campaign/{campaign_id}/voucher_code]

+ Parameters
    + campaign_id: 10l176 - ID of the campaign

### List all Voucher Codes [GET]

View all Voucher Codes attached to the Campaign.

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + voucher_codes (array[Voucher Code Wrapper])

### Create Voucher Codes [POST]

Create new Vouchers by passing each Voucher object within a `voucher_codes` array. A `voucher_code` string to define
the actual code must be passed with each object, and to allocate the Voucher to specific Groups, pass the Group ids
in a `commission_groups` array.

+ Request (application/json; charset=utf-8)
    + Attributes
        + voucher_codes (array)
            + (Voucher Code Base)
                + voucher_code: specialoffer69

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Voucher Code Wrapper)

### Update Voucher Codes [PUT]

Update Vouchers by referencing the `voucher_code_id` in each Group object within the `voucher_codes` array.

+ Request (application/json; charset=utf-8)
    + Attributes
        + voucher_codes (array)
            + (Voucher Code Base)
                + voucher_code_id: 111111l1000015 - ID of the voucher code

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Voucher Code Wrapper)

## Voucher Code [/campaign/{campaign_id}/voucher_code/{voucher_code_id}]

+ Parameters
    + campaign_id: 10l176 - ID of the campaign
    + voucher_code_id: 111111l1000015 - ID of the voucher code

+ Attributes (object)
    + voucher_code_id: 111111l1000015 - ID of the voucher code
    + campaign_id: 10l176 - ID of the campaign
    + Include Voucher Code Base
    + active (YesOrNo)
    + on_expiry: ignore
    + on_invalid_user: ignore

### Retrieve a Voucher Code [GET]

Outputs the specified Voucher Code.

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Voucher Code Wrapper)
